### ISSUE TITLE
ash: service: not found

### ISSUE THREAD

**Issue by KiloDoubleMike** [porech/roborock-oucher#15]
Unable to start service on Roborock S5. It seems that the service command doesn't exist on the robots shell. What should I do?

**Comment by ale-rinaldi** [comment]
Hello @KiloDoubleMike ,

I'm really sorry but it's difficult for me to help on this since I don't have the device and I can't test it. I see some people solved it by running it via other tricks (like using cron), but I recommend you ask on the [dustcloud Telegram group](https://t.me/joinchat/Fl7Mm0iEV7Pgf9ngDyly-g) for help from people owning the same device.

Thank you!
