### ISSUE TITLE
i8+?

### ISSUE THREAD

**Issue by alui07** [porech/roborock-oucher#21]
Hello all,

I recently bought an i8+ from Costco and wanted to do something similar, I've been looking at some of the other repos: rooting, etc. and wanted to get a rough idea of what it takes to develop something similar in the case that this stuff doesn't exactly work for the i8. I have a few years of experience in software development, but I have no experience with any of this. What would it take to develop something similar?

**Comment by ale-rinaldi** [comment]
Hi @alui07 ,

well, Oucher itself is really, really simple. In its basic form, it watcher for a log file and, every time a line is added, it checks if it's a bumper press (luckily, it gets logged). It it is, it picks a random WAV file from a directory and plays it. Just this 

Over time, I made it just a little more complex. For example, it now watcher multiple log files and searches for bump lines in different patterns, to support a wider range of devices. And I made it directly access to the soundcard, using a Golang library, so that it doesn't require an audio player to be installed (on some models, it became hard to install stuff).

So what you need to do? Well, of course you start with rooting it. Then, the hardest work is look at all the log files while it's cleaning, bump into it on purpose and understanding what and where it logs when it happens. You may need to tweak settings, like increase log verbosity, to have it logged. If you're lucky, and it gets logged also on your model, you're done! You can just come here with what you've found and I'll add it to Oucher itself, or you can create a fork, as you prefer. Anyway what needs to need changed is just the log parsing, the rest of the code should be ok on any Linux device.

If it doesn't log bumps in any way, well, it gets harder. I guess you'd need to access the device directly, but I would have no clue on where to start as of now, to be honest :)

Please let me know how it goes!

Thanks
