### ISSUE TITLE
Not working on Roborock S7

### ISSUE THREAD

**Issue by MarcPot** [porech/roborock-oucher#25]
The oucher does not seem to work on my robot.
No ouch at all.

[NAV_normal.log](https://github.com/porech/roborock-oucher/files/11304915/NAV_normal.log)
[NAV_normal_pl9.log](https://github.com/porech/roborock-oucher/files/11304916/NAV_normal_pl9.log)
[NAV_TRAP_fprintf.log](https://github.com/porech/roborock-oucher/files/11304917/NAV_TRAP_fprintf.log)
[NAV_TRAP_normal.log](https://github.com/porech/roborock-oucher/files/11304918/NAV_TRAP_normal.log)

**Comment by ale-rinaldi** [comment]
Hi @MarcPot ,

thanks for your report! From a first look at your logs, it seems like the S7 is logging with the same format as the other ones, but in `NAV_normal_pl9.log` instead of `NAV_normal.log`, that I don't watch by default. I can add it to the default watched file, can you confirm me that it's still in `/run/shm`?

Thank you

**Comment by MarcPot** [comment]
That worked!

**Comment by ale-rinaldi** [comment]
Glad to hear this! I update the executable in the repository to watch that file by default; can you please confirm that with the latest executable it works even without modifying the config file?

Thanks

**Comment by MarcPot** [comment]
Apologies did not have the time to test it. Just did and it's working!

**Comment by ale-rinaldi** [comment]
Thanks for the feedback! :)
